
swipeRate = 200
appiumServerURL = http://127.0.0.1:4723

## Platform Caps
platformType = Android
platformVersion = 13.0
android_automationDriver = UiAutomator2
ios_automationDriver = XCUITEST

## Devices Caps
android_deviceName = emulator-5554
android_deviceID =emulator-5554
ios_deviceName = iPhone 17 Pro Max
ios_deviceID = F887B8C7-45A8-454C-B7DF-046F11ED995A

## Application Caps
android_appPackage = com.swaglabsmobileapp
android_appActivity = com.swaglabsmobileapp.SplashActivity
android_appInstaller = Android.SauceLabs.apk

ios_bundleId = com.saucelabs.SwagLabsMobileApp
ios_appInstaller = iOS.Simulator.SauceLabs.zip


## General Caps
autoGrantPermission = true
noReset=false
fullReset=false