
appiumServerURL = http://127.0.0.1:4723

        ## Platform Caps
platformType = Android
platformVersion = 13.0
##UiAutomator2 or XCUITEST
automationDriver = UiAutomator2

        ## Devices Caps
deviceName = emulator-5554
deviceID = emulator-5554

        ## Application Caps
appPackage = com.swaglabsmobileapp
appActivity = com.swaglabsmobileapp.SplashActivity
bundleId = null

        ## General Caps
autoGrantPermission = true
noReset = true
fullReset = false